services:
  # Веб-сервис с FastAPI приложением
  - type: web
    name: pricladnoy-python-url-shortener
    runtime: python
    plan: free
    region: frankfurt
    branch: project_3
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pricladnoy-python-db
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: pricladnoy-python-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30

  # PostgreSQL база данных
  - type: postgresql
    name: pricladnoy-python-db
    plan: free
    region: frankfurt
    ipAllowList: []

  # Redis
  - type: redis
    name: pricladnoy-python-redis
    plan: free
    region: frankfurt
    maxmemoryPolicy: noeviction
    ipAllowList: []
